---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
  - repo: local
    hooks:
      - id: validate-contracts
        name: validate contracts
        entry: python -m pytest
        language: system
        pass_filenames: false
      - id: yamllint
        name: yamllint
        entry: yamllint .
        language: system
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        pass_filenames: false
